// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameEvent = "events"

// Event mapped from table <events>
type Event struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;type:text;not null" json:"name"`
	Description  string    `gorm:"column:description;type:text;not null" json:"description"`
	DateTime     time.Time `gorm:"column:date_time;type:timestamp with time zone;not null;index:idx_events_date_time,priority:1" json:"date_time"`
	TotalTickets int       `gorm:"column:total_tickets;type:integer;not null" json:"total_tickets"`
	TicketPrice  float64   `gorm:"column:ticket_price;type:numeric(12,2);not null" json:"ticket_price"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
