// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameTicket = "tickets"

// Ticket mapped from table <tickets>
type Ticket struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	EventID   int64     `gorm:"column:event_id;type:bigint;not null;index:idx_tickets_event_id,priority:1" json:"event_id"`
	UserID    int64     `gorm:"column:user_id;type:bigint;not null;index:idx_tickets_user_id,priority:1" json:"user_id"`
	Status    string    `gorm:"column:status;type:ticket_status;not null;index:idx_tickets_status,priority:1;default:pending" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Ticket's table name
func (*Ticket) TableName() string {
	return TableNameTicket
}
