// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/google/uuid"
)

const TableNameTicketDone = "ticket_done"

// TicketDone mapped from table <ticket_done>
type TicketDone struct {
	ID            uuid.UUID `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	EventID       int64     `gorm:"column:event_id;type:bigint;not null;index:idx_ticket_done_event_id,priority:1" json:"event_id"`
	UserID        int64     `gorm:"column:user_id;type:bigint;not null;uniqueIndex:idx_ticket_done_user_id_client_order_id_updated_at,priority:3;index:idx_ticket_done_user_id,priority:1" json:"user_id"`
	ClientOrderID string    `gorm:"column:client_order_id;type:character varying(255);not null;uniqueIndex:idx_ticket_done_user_id_client_order_id_updated_at,priority:1" json:"client_order_id"`
	Status        string    `gorm:"column:status;type:ticket_status;not null;index:idx_ticket_done_status,priority:1;default:pending" json:"status"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp with time zone;primaryKey;uniqueIndex:idx_ticket_done_user_id_client_order_id_updated_at,priority:2;index:ticket_done_updated_at_idx,priority:1;default:now()" json:"updated_at"`
}

// TableName TicketDone's table name
func (*TicketDone) TableName() string {
	return TableNameTicketDone
}
