// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import "time"

const TableNameUserTicket = "user_ticket"

// UserTicket mapped from table <user_ticket>
type UserTicket struct {
	EventID     int64     `gorm:"column:event_id;type:bigint;primaryKey" json:"event_id"`
	UserID      int64     `gorm:"column:user_id;type:bigint;primaryKey;index:idx_user_ticket_user_id,priority:1" json:"user_id"`
	TicketCount int64     `gorm:"column:ticket_count;type:bigint;not null;default:0" json:"ticket_count"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

func (*UserTicket) TableName() string {
	return TableNameUserTicket
}
