// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import "time"

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;type:text;not null" json:"name"`
	Email        string    `gorm:"column:email;type:text;not null;index:idx_users_email_lower,unique" json:"email"`
	PasswordHash string    `gorm:"column:password_hash;type:text;not null" json:"-"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
